apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo-app
  template:
    metadata:
      labels:
        app: spring-boot-demo-app
    spec:
      containers:
        - name: spring-boot-demo-app
          image: demoapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app.message
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: api.key
#            - name: SPRING_PROFILES_ACTIVE
#              value: 'prod'
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-demo-app
